version: 2
jobs:
  build:
    working_directory: /interlockmon
    docker:
      - image: golang
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and Push
          command: |
            TAG=latest
            docker build -t oldrob/interlockmon-agent:$TAG -f agent.Dockerfile .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push oldrob/interlockmon-agent:$TAG
            docker build -t oldrob/interlockmon-splunk:$TAG -f splunk.Dockerfile .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push oldrob/interlockmon-splunk:$TAG            